name: brefnews
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.1.2
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  shimmer: ^3.0.0
  go_router: ^13.0.0  
  url_launcher: ^6.1.11
  marvelous_carousel: ^0.0.16
  google_sign_in: ^6.1.5
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  carousel_slider: ^5.1.1
  stacked_card_carousel: ^0.0.4
  phosphor_flutter: ^2.1.0
  file_picker: ^10.3.3
  intl_phone_field: ^3.2.0
  animations: ^2.0.11
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3


  flutter_localizations:
    sdk: flutter
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  video_player: ^2.10.0
  chewie: ^1.13.0
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.4  

  
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon" 
  ios: true 
  image_path: "assets/real.jpg"
  

flutter:
  assets:
    - assets/brefnews.png
    - assets/timelines.png
    - .env

  
  uses-material-design: true
